version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "Europe/Kiev"
      time: "09:00"
    pull-request-branch-name:
      separator: "_"
    labels:
      - "Front-end"
      - "Need Review"
